### ISSUE TITLE
user defined background fasta

### ISSUE THREAD

**Issue by unfashionable** [simonvh/gimmemotifs#31]
Quick question: If I give gimmemotif with my own background sequences, how does gimmemotif run MEME, Weeder (the tools that cannot accept user-defined background)?

**Comment by simonvh** [comment]
In that case gimme motifs will use the background only to determine which motifs are significantly enriched. Only the motifs that are enriched compared to your own background will be used for clustering and showns in the final report. So MEME etc. will not use the background, but it's used in the steps after.

**Comment by unfashionable** [comment]
Thanks!
