### ISSUE TITLE
hg38.fa contains multiple sequences

### ISSUE THREAD

**Issue by croth1** [simonvh/gimmemotifs#48]
Tried to run following command:
`gimme genome /cbscratch/croth1/gimmemotifs/genomes/hg38  hg38`

with the latest version from bioconda
`gimmemotifs               0.10.0b6         py27pl5.22.0_1    bioconda`

This is the result:
```
Retrieving gene annotation for hg38
Expecting 10 words line 1 of /dev/stdin got 9
cut: write error: Broken pipe
Downloading hg38 genome
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/chromFa.tar.gz
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
´Unpacking
Creating index
Sorry, can only index genomes with one sequence per FASTA file
/cbscratch/croth1/gimmemotifs/genomes/hg38/hg38/hg38.fa contains multiple sequences
```

**Comment by simonvh** [comment]
Thanks for reporting this issue. I will release a fixed version as soon as I have time. 
In the meanwhile, you can download the hg38 genome from [here](http://hgdownload.cse.ucsc.edu/goldenPath/hg38/chromosomes/), unpack the fasta files and index the genome directory with `gimme index`.

**Comment by simonvh** [comment]
This is fixed in the new release of GimmeMotifs on bioconda:

```
$ conda create -n gimme python=2 gimmemotifs=0.10.0=py27_0
```
