### ISSUE TITLE
gimme motifs output

### ISSUE THREAD

**Issue by tamerawwad** [simonvh/gimmemotifs#68]
Hi Simon,
I run gimme motifs on two different bed files of mm10 genome .. for one the output was absolutely fine as expected however the other one gave me weird output file with no error message though.
the output file contains:
gimmemotifs.log file and intermediate folder which contains (all_motifs.pfm, bg.gc.fa, bg.random.fa, input.bed, localization.fa, prediction.bed, prediction.bg.fa, prediction.fa, significant_motifs.pfm, stats.gc.txt, stats.random.txt, validation.bed, validation.fa).
this is the code I run:
$gimme motifs  chr18.bed -g mm10 -n gimme.motif

I don't know what could be possibly wrong.
any ideas?
thanks much
TA

**Comment by simonvh** [comment]
I'm afraid I can't tell from this description. Could you post the `gimmemotifs.log` file, the input file (`chr18.bed`) and the version of GimmeMotifs that you use?

**Comment by tamerawwad** [comment]
thanks Simon for the response.. 
my log file:
[gimmemotifs.log](https://github.com/simonvh/gimmemotifs/files/2353000/gimmemotifs.log)


and the head of my bed file is:
chr18	3039305	3039771	19.44981
chr18	3176970	3177312	16.88641
chr18	3280331	3281072	85.77558
chr18	3328940	3329436	20.31606
chr18	3337391	3337959	204.70624
chr18	3427930	3428601	62.61533
chr18	3495161	3495988	176.78157
chr18	3497345	3497689	11.91403
chr18	3507028	3507980	241.33618
chr18	3794678	3795086	28.53855


GimmeMotifs  version :
gimmemotifs-0.12.0

**Comment by simonvh** [comment]
It seems the second run finished without problems, but found no significant motifs. This should also have been the last message on the screen (stdout). From you BED file it looks like you have relatively broad regions. I don't know what kind of data this is, but is there a way that you can narrow these down to ~100-200bp? For instance, a peak summit from ChIP-seq or accessibility data.

**Comment by tamerawwad** [comment]
thanks much Simon

**Comment by simonvh** [comment]
Closing, feel free to re-open if you have any more questions.
